version: "3.8"
volumes:
  shared-web-app:
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: isucon7-qualify-web
    ports:
      - 10080:80
    volumes:
      - shared-web-app:/shared-web-app
  app:
    build: ./app
    container_name: isucon7-qualify-app
    environment:
      ISUBATA_DB_HOST: isucon7-qualify-db
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
    volumes:
      - shared-web-app:/shared-web-app
    command: ./entrypoint.sh
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.prod
    container_name: isucon7-qualify-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: isubata
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
