version: "3.8"
volumes:
  shared-web-app:
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: isucon7-qualify-init-web
    ports:
      - 10080:80
    volumes:
      - shared-web-app:/shared-web-app
  app:
    build: ./app
    container_name: isucon7-qualify-init-app
    environment:
      ISUBATA_DB_HOST: isucon7-qualify-init-db
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
    volumes:
      - ./app:/app
      - shared-web-app:/shared-web-app
    tty: true
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: isucon7-qualify-init-db
    ports:
      - 3306:3306
