version: "3.8"
volumes:
  railway_db_data:
services:
  api:
    build: ./docker/api
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/app
  db:
    image: mysql:5.7
    volumes:
      - railway_db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.25.5
    volumes:
      - ../openapi/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml
    ports:
      - 8080:8080
