version: '3.7'

services:
  app:
    build: ./app
    tty: true
    volumes:
      - ./app:/go/src/app
    ports:
      - "3000:3000"
  db:
    build: ./db
    command: "--innodb_use_native_aio=0"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
