version: '3.7'

services:
  app:
    build: .
    tty: true
    volumes:
      - .:/go/src/station
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306
