language: php

dist: bionic

php:
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly
