version: "3.8"
services:
  app:
    container_name: laravel-template-app
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../app:/app
      - ../app-data:/app-data
