version: "3.8"
volumes:
  app_node_modules:
services:
  app:
    image: node:14.2.0-buster
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    tty: true
  redis:
    image: redis:6.0.3
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
