version: "3.8"
volumes:
  nginx-frontend-shared:
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3306:3306"

  api-server:
    build: ./python
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    volumes:
      #- ../mysql/db:/go/src/mysql/db
      - ./fixture:/fixture
    environment:
      MYSQL_DBNAME: isuumo
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      MYSQL_HOST: mysql
      SERVER_PORT: 1323
    ports:
      - "1323:1323"
    depends_on:
      - mysql
    tty: true
    command: python app.py

  frontend:
    build: ./isucon10-qualify/webapp/frontend
    volumes:
      - nginx-frontend-shared:/frontend/out

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      #- ../logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - nginx-frontend-shared:/www/data
    ports:
      - "8080:80"
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - http://api-server:1323/api/estate/search/condition
    environment:
      API_SERVER: api-server
    depends_on:
      - frontend
    command: >
      /bin/sh -c
      "envsubst '
      $$API_SERVER
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
