version: "3"
services:
  #dev:
  #  build:
  #    context: .
  #    dockerfile: ./Dockerfile.dev
  #  container_name: matome-dev
  minio:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    container_name: matome-minio
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    ports:
      - 19000:9000
    volumes:
      - ./docker/minio/data:/export
    command: server /export
