version: "3"
services:
  nginx:
    image: nginx:1.19.6
    container_name: matome-frontend-content-server
    ports:
      - 9999:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/shared:/usr/share/nginx/html:ro
